In [23]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [29]:
import numpy as np
arr= np.array([[1,2,3],[4,5,6]])
res= arr**2
print(res)


[[ 1  4  9]
 [16 25 36]]


In [37]:
print(res.shape)

(2, 3)


In [115]:
arr =np.array([[1,2,3,4,5,6,7,8,9],
               [10,11,12,13,14,15,16,17,18],
               [19,20,21,22,23,24,25,26,27],
               [28,29,30,31,32,33,34,35,36],
               [37,38,39,40,41,42,43,44,45],
               [46,47,48,49,50,51,52,53,54]])
res=arr[3:,::4]
print(res)

[[28 32 36]
 [37 41 45]
 [46 50 54]]


In [117]:
arr.reshape(9,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54]])